vich_uploader:
    db_driver: orm

    mappings:
       profile_img:
           uri_prefix: /images/profile_imgs
           upload_destination: '%kernel.project_dir%/public/images/profile_imgs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
